### ISSUE TITLE
Console Error Can't do anything

### ISSUE THREAD

**Issue by rhys19** [DevLanceGood/server-meeting#1]
I keep getting this issue everytime i even tried the first version but got the same any suggestions?

`cfx> Error running system event handling function for resource servermeeting: citizen:/scripting/lua/scheduler.lua:41: Failed to execute thread: server.lua:33: bad argument #1 to 'for iterator' (table expected, got nil)
stack traceback:
        [C]: in for iterator 'for iterator'
        server.lua:33: in function 'isAdmin'
        server.lua:21: in upvalue 'handler'
        citizen:/scripting/lua/scheduler.lua:175: in function <citizen:/scripting/lua/scheduler.lua:174>
stack traceback:
        [C]: in function 'error'
        citizen:/scripting/lua/scheduler.lua:41: in field 'CreateThreadNow'
        citizen:/scripting/lua/scheduler.lua:174: in function <citizen:/scripting/lua/scheduler.lua:138>`

**Comment by rhys19** [comment]
when i type any command: `Error running call reference function for resource servermeecfx> ting: citizen:/scripting/lua/scheduler.lua:351: server.lua:33: bad argument #1 to 'for iterator' (table expected, got nil)
stack traceback:
        [C]: in for iterator 'for iterator'
        server.lua:33: in function 'isAdmin'
        server.lua:6: in upvalue 'ref'
        citizen:/scripting/lua/scheduler.lua:337: in function <citizen:/scripting/lua/scheduler.lua:336>
        [C]: in function 'xpcall'
        citizen:/scripting/lua/scheduler.lua:336: in function <citizen:/scripting/lua/scheduler.lua:335>
stack traceback:
        [C]: in function 'error'
        citizen:/scripting/lua/scheduler.lua:351: in function <citizen:/scripting/lua/scheduler.lua:322>`

**Comment by DevLanceGood** [comment]
Resolved. I'm supremely stoopid and forgot to include the config file as a shared lua file (on both the client and server).

Sowwy!
